### ISSUE TITLE
Add "search" repo action

### ISSUE THREAD

**Issue by rodyhaddad** [ProLoser/Github-Omnibox#10]
`user/repo search stuff`

**Comment by ProLoser** [comment]
I sort of think we should alias ? to search or something

**Comment by ProLoser** [comment]
https://github.com/ProLoser/Github-Omnibox/commit/3be3fb9eb19ccdb7767ef621c20bec05a511cbc4#diff-0f1526faad53cedf9ff8273874f3c343R189
