### ISSUE TITLE
Fix bad URL redirect for new users trying to do OAuth

### ISSUE THREAD

**Issue by ProLoser** [ProLoser/Github-Omnibox#15]
A few times I've noticed that if someone installs the plugin on a fresh browser, the OAuth redirect url is wrong, and I was forced to manually re-auth the user. This is a critical bug.

**Comment by rodyhaddad** [comment]
This seems to do the trick

**Comment by ProLoser** [comment]
But what if you need to de-auth and re-auth?

**Comment by rodyhaddad** [comment]
Works for me.  

the `client_id/secret` and `api_scope` never change

`this.api.authorize(...)` gets us the access token (auth)
and `this.api.clearAccessToken()` removes it (unauth)
