### ISSUE TITLE
Remove auth permissions from Github OAuth

### ISSUE THREAD

**Issue by ProLoser** [ProLoser/Github-Omnibox#17]
We don't need to write to your account and it will scare less people.

**Comment by sheldond** [comment]
+1 I agree, I am scared :)

**Comment by ProLoser** [comment]
Apparently this isn't possible unless we don't collect your private repo
information.

Although we use all the info readonly private repos can't be accessed
otherwise.

Should we give users the option if they are paranoid? Seems like too much
information.

An options page with an explanation before might be better?

**Comment by sheldond** [comment]
Thanks for the reply! Hmm, this seems like a limitation on Github's end. I wonder if we could open an issue for Github to look at?

(My main concern is that my account is linked to organization repos that I do not own and I'd rather not expose write-access to them.)

**Comment by ProLoser** [comment]
Since the code is open you are free to verify that no write actions are
being performed. That said, yes it might be a good idea to see if Github
would be willing to address the issue (albeit unlikely).

If they DO in fact respond that it is possible to do I am more than happy
to implement it.

**Comment by sheldond** [comment]
Hi ProLoser, I went ahead and installed the extension, unfortunately it does not seem to be working. The first time I installed the extension I denied oauth access, then I reinstalled it and allowed oauth, could this be a bug related to that?

**Comment by ProLoser** [comment]
Define "it doesn't seem to be working". What did you try to do exactly?

**Comment by sheldond** [comment]
I'm sorry for the vague comment, that wasn't helpful :) 

Here are some screenshots, I expected some of my repos to show in the dropdown but nothing except generic search terms appear. Am I using incorrect syntax or is this a bug?

https://drive.google.com/file/d/0B2rWOkxbWpeKS19ZMklSbmhCQjA/edit?usp=sharing
https://drive.google.com/file/d/0B2rWOkxbWpeKVXhMbldZUW4zazA/edit?usp=sharing

Thanks!

**Comment by rodyhaddad** [comment]
@sheldond doing `gh /event` should show you all your repos that start with `event`, which is not working for you

Try this:
If you do `gh my repositories`, does it open your github repository page?

If not, it means that you're not authed (the extension doesn't know your username), so do: `gh my auth`

If you actually do get to your repo page, it means that the extension's cache didn't get filled with your repos while you're authed, so do: `gh my reset` to fix that

Does it work now? Which case were you in?

**Comment by sheldond** [comment]
Thanks!

`gh my repositories` does not work, it takes me to https://github.com/null?tab=repositories

`gh my auth` also does not work, it shows me a popup dialog that says "You can unauthorize at any time by doing "gh my unauth" but it takes me to the about:blank page.

`gh my reset` appears to have no effect.

I did these tests with all other extensions disabled. 

Note that I am using Chrome 33.0.1710.0 Canary, perhaps that is the issue?

Thanks again, this seems like a very useful extension.

**Comment by ProLoser** [comment]
Nope, looks like authorization was broken recently somehow (when I try to
re-auth I get a blank page too).

We need to make our interface less cryptic to use lol. We REALLY need an
options page.

On Fri, Nov 15, 2013 at 11:30 AM, Sheldon Dueck notifications@github.comwrote:

> Thanks!
> 
> gh my repositories does not work, it takes me to
> https://github.com/null?tab=repositories
> 
> gh my auth also does not work, it shows me a popup dialog that says "You
> can unauthorize at any time by doing "gh my unauth" but it takes me to the
> about:blank page.
> 
> gh my reset appears to have no effect.
> 
> I did these tests with all other extensions disabled.
> 
> Note that I am using Chrome 33.0.1710.0 Canary, perhaps that is the issue?
> 
> Thanks again, this seems like a very useful extension.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ProLoser/Github-Omnibox/issues/17#issuecomment-28596655
> .

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by ProLoser** [comment]
@rodyhaddad maybe this has to do with my manifest change that added more URLs to the whitelist? Which, btw also needs to be updated to include github.io

**Comment by ProLoser** [comment]
@sheldond I'm pushing the fixed version right now. Sorry it took me so long to get to.

**Comment by ProLoser** [comment]
Closing this because after reviewing the docs a few times I don't think this is doable.

**Comment by sheldond** [comment]
It's working now, beautiful, thanks!
