### ISSUE TITLE
Disable travis / dependency links for private repos

### ISSUE THREAD

**Issue by ProLoser** [ProLoser/Github-Omnibox#19]
This is what happens when the repo is private: 
![screen shot 2013-09-09 at 11 53 48 am](https://f.cloud.github.com/assets/67395/1109490/5053a62c-1981-11e3-80e2-722e973c7a97.png)

**Comment by rodyhaddad** [comment]
What about adding `alt="N/A"` to the images?

**Comment by ProLoser** [comment]
Does that show up? Maybe we can just search the dom for a css class, like
the one used on the icon?

**Comment by ProLoser** [comment]
8c348b75ba831c2d3d19635024b52abcdca71fa4
