### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by techniq** [ProLoser/Github-Omnibox#2]
I would rather setup an OAuth authorization than supply my username/password for the extension.  It appears github.js supports both - https://github.com/michael/github#usage

**Comment by ProLoser** [comment]
Checkout v0.4.0

Now has OAuth support!

**Comment by techniq** [comment]
Great, although I just tried and I get the following error after clicking OK on "Would you like to Authorize Github-Omnibox for personalized suggestions?"

This webpage is not found
No webpage was found for the web address: chrome-extension://jbfhklldhgbomclinhlgbmjjiimafolo/options.html
Error 6 (net::ERR_FILE_NOT_FOUND): The file or directory could not be found.

**Comment by ProLoser** [comment]
Crap.

On Tue, Jul 2, 2013 at 1:27 PM, Sean Lynch notifications@github.com wrote:

> Great, although I just tried and I get the following error after clicking
> OK on "Would you like to Authorize Github-Omnibox for personalized
> suggestions?"
> 
> This webpage is not found
> No webpage was found for the web address:
> chrome-extension://jbfhklldhgbomclinhlgbmjjiimafolo/options.html
> Error 6 (net::ERR_FILE_NOT_FOUND): The file or directory could not be
> found.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ProLoser/Github-Omnibox/issues/2#issuecomment-20373537
> .

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by ProLoser** [comment]
I just pushed v0.4.2 right now should have that fixed. Nice catch.

**Comment by ProLoser** [comment]
You can type `gh my auth` to re-auth

**Comment by techniq** [comment]
gh my auth worked.  Did you completely remove the options page now, as I don't see it under `chrome://extensions/`

Also, while `gh my followers` works (takes me to https://github.com/techniq/followers), but `gh my repositories` takes me to `https://github.com/search?q=my%20repositories`, similarly `gh my starred` takes me to `https://github.com/search?q=my%20starred`, `gh my activities`...

**Comment by ProLoser** [comment]
Yes, I removed the options page as there is no longer a need for it at the moment and I just wanted to keep things minimal atm.

I will test your mentioned issues. I am finding the thing is very buggy and breaks inconsistently.

**Comment by ProLoser** [comment]
Looks like the cases you mention, although show up in suggestions, aren't actually coded out. They are a behavior of my trying to merge the `@whatever` code and `my` code. I will look into it later tonight to see if i can standardize and clean things up.

`my stars` should work though.

**Comment by techniq** [comment]
No problem, thanks for being attentive :).  Just thought I'd throw some feedback your way.

**Comment by ProLoser** [comment]
I'm more than appreciative. Feel free to also throw requests out there too.
