### ISSUE TITLE
`gh gist 123123` should not automatically add your username

### ISSUE THREAD

**Issue by ProLoser** [ProLoser/Github-Omnibox#21]
Although all gists are namespaced by owner, they are still unique (I think). I would like to be able to specify a gist without having to specify the owner, so if we direct to `gist.github.com/123123` github will automatically redirect to the proper owner.

**Comment by rodyhaddad** [comment]
Hm, would have to consider that someone with the username `123123` can exist (and actually does), so we would be opening his profile.
We could fetch the owner of a gist id [from the api](http://developer.github.com/v3/gists/#get-a-single-gist) to remove that concern

**Comment by ProLoser** [comment]
I don't think we bother with users, plus we could just support @123123

**Comment by ProLoser** [comment]
39709a0192fe3a5cd2c1fe2ca80c885829e3e2f5
