### ISSUE TITLE
Add onerror attribute to status images

### ISSUE THREAD

**Issue by ProLoser** [ProLoser/Github-Omnibox#23]
`<img onerror="this.src='some-fixed-asset'">` would solve problems of status images for certain repos 404'ing.

I also think david-dm should be re-added. I removed it because it only covers Node, but gemnasium handles ruby and node, but now I've realized that david doesn't require you to register the package while gemnasium does.

**Comment by ProLoser** [comment]
I'm getting this message with the updated code:

``` js
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' https://github.global.ssl.fastly.net https://jobs.github.com https://ssl.google-analytics.com https://collector.githubapp.com https://analytics.githubapp.com".
```

**Comment by rodyhaddad** [comment]
Wouldn't an `alt` attribute on the `img` do the trick?

**Comment by ProLoser** [comment]
I tried, no. But I already fixed it in the latest version.

**Comment by rodyhaddad** [comment]
in aa56bde31b55f2fda3a9744ee365faab535802f0, great :+1:
