### ISSUE TITLE
Cannot see options, unsure how to use

### ISSUE THREAD

**Issue by rayshan** [ProLoser/Github-Omnibox#31]
Hi, thanks for your hard work on this. I installed on Chrome 33.0.1750.46 beta. I am unsure whether there's supposed to be an options page on Chrome Extensions page. Also unsure how to invoke the omnibox in Chrome address bar. I do see the Travic CI / David DM badges on a repo's home page so something must be working.

![screen shot 2014-01-25 at 11 34 23 am](https://f.cloud.github.com/assets/3760840/2002488/37bd909e-85f8-11e3-93c0-604e4a43d161.png)

 Advice please?

**Comment by ProLoser** [comment]
At this time we don't have any options. To trigger an omnibox extension just type `gh[space]` into chrome's address bar. We really need to have some sort of help page open up when you first install.

**Comment by ProLoser** [comment]
Hey I updated the README. I know this is pretty lame but just been super busy. If you want to help us out by cleaning up help.html or something for us that would be super appreciated!

I'm not 100% sure the best way to break down all the shortcuts we support short of making a screencast lol.
