### ISSUE TITLE
"gh /" doesn't allow for private repositories

### ISSUE THREAD

**Issue by cluther** [ProLoser/Github-Omnibox#37]
I find that even after I successfully authenticate with "gh[tab]my auth" I'm still not presented with private repositories of organizations to which I belong when I do "gh[tab]/".

**Comment by ProLoser** [comment]
Do `gh my reset` to update your cache. We should have it occur automatically

**Comment by cluther** [comment]
@ProLoser: Thanks, but that didn't make any difference for me.

**Comment by ProLoser** [comment]
If you do `gh my auth` and let all the page popups and alerts go through it should work. It seems to be working for me. Is there any more information you can give us to help you? Or perhaps you can screencast or something?
