### ISSUE TITLE
Badges aren't shown in Chrome 43

### ISSUE THREAD

**Issue by tophf** [ProLoser/Github-Omnibox#46]
![badge](https://cloud.githubusercontent.com/assets/1310400/6746321/6948b3b8-ced7-11e4-81d6-23fe414d9467.png)

![cert](https://cloud.githubusercontent.com/assets/1310400/6746322/6c5bd26a-ced7-11e4-89f6-a1a741fbcc19.png)

Is there anything you can do about that?

**Comment by ProLoser** [comment]
I'm having trouble reproducing this. 
![screen shot 2015-03-19 at 11 04 17 pm](https://cloud.githubusercontent.com/assets/67395/6746835/4f095912-ce8c-11e4-8e91-ba8bb0fd2925.png)

That URL is https so if the certificate is bad I would imagine it's the fault of david-dm. If you don't use or care about david-dm you can actually now remove it by clicking on that `Github Omnibox` link at the bottom.

**Comment by tophf** [comment]
Thanks. I guess, if your screenshot is from Chrome stable or beta, it means that Chrome 43 dev started to reject the outdated certificates.
