### ISSUE TITLE
Default suggestions is misleading

### ISSUE THREAD

**Issue by ProLoser** [ProLoser/Github-Omnibox#5]
Right now the default suggestion is from the old behavior where if you hit [enter] the first suggestion will be used. It appears to now just use what you have typed in so far (as I realized I asked for before).

The _problem_ is that the default suggestion was not changed, so it misrepresents the behavior that will occur when I hit [enter]. There is also a bad side-affect. If I start using the arrows to move through suggestions, and go back up to the default one, instead of changing the text from 'my' to 'my dash' it will just go back to 'my' again. And if I hit [return] the default suggestion will not actually be used.

I believe that the default suggestion should ALWAYS tell you what is going to happen if you hit [enter] right there, with what you have typed in. If we auto-select the first suggestion, then that's fine, but if we have that disabled, it should fall back to saying that it will search or whatever.

**Comment by ProLoser** [comment]
![screen shot 2013-07-10 at 11 19 51 am](https://f.cloud.github.com/assets/67395/776828/eecd9980-e98d-11e2-8ee2-029773dd6b4b.png)

**Comment by rodyhaddad** [comment]
> I believe that the default suggestion should ALWAYS tell you what is going to happen if you hit [enter] right there, with what you have typed in.  

This is the behaviour right now.
If I type `my`, the first suggestions is `my dash` and when I hit [enter], it takes me to my dashboard as expected.

---

> so it misrepresents the behavior that will occur when I hit [enter]  

Hm, in my tests it doesn't. If I type `ProLoser/Github-Omnibox iss`, it opens the issues of this repository as suggested.  
Maybe I've missed a case where the 'auto-completion' doesn't work?

**Comment by ProLoser** [comment]
This is not the current behavior.

If I type in `my` and hit enter, it takes me here: https://github.com/search?q=my
If I type in `ProLoser/Github-Omnibox iss` it takes me here: https://github.com/search?q=ProLoser/Github-Omnibox%20is

**Comment by rodyhaddad** [comment]
Then you've got something wrong with your extension version.
Make sure you have the Chrome web store version disabled (?)

For me `my` and `ProLoser/Github-Omnibox iss` works as I described above.
