### ISSUE TITLE
Open source the last version (1.7.x)

### ISSUE THREAD

**Issue by douglasduteil** [ProLoser/Github-Omnibox#51]
Hi @ProLoser 

Following #50 I'm starting to work on the new github design compatibility.
Apparently the last available version on this repo (1.4.6) is different that the one in the Chrome store (1.7.0)

Can you push the changes so I can be up to date ? :+1: 

Thanks.
Douglas.

**Comment by ProLoser** [comment]
Actually I think the atomic searching branch is that. I'm not 100% sure what's on the chrome store unfortunately, and the plugin has seemed a little broken for me lately.

**Comment by ProLoser** [comment]
Wait @douglasduteil are you sure the latest is 1.4.6? This is the version in manifest: https://github.com/ProLoser/Github-Omnibox/blob/gh-pages/manifest.json#L5

**Comment by ProLoser** [comment]
Feel free to reopen if this is wrong

**Comment by douglasduteil** [comment]
Oops sry. My fork was outdated :blush:

**Comment by douglasduteil** [comment]
Thanks
