### ISSUE TITLE
keeps reprompting for oauth

### ISSUE THREAD

**Issue by blaenk** [ProLoser/Github-Omnibox#55]
I already authorized it but every time I trigger the omnibox it shows the pop up asking if I'd like to authorize it. Could this be related to the recent name change? Perhaps it keeps checking for the previous name perhaps?

**Comment by ProLoser** [comment]
Yeah I need to fix this. Must have a regression around setting  the authorized flag

**Comment by spalger** [comment]
+1

**Comment by ProLoser** [comment]
Yeah I know, totally planning on tackling this ASAP, been super busy. Had a film shoot this past weekend. Will do my best to address this tonight.

**Comment by ProLoser** [comment]
Can you guys test 1.7.2 and see if it's fixed now?

**Comment by blaenk** [comment]
Confirmed working, unless the following is caused by this.

By the way, if I type `gh /pref` it does show a suggestion for a hypothetical private repo called `prefix`, but pressing enter on it just goes to a repo `pref`. Is that intended? Is there a way that can be fixed so that, since that first suggestion is chosen, it'll go to that option when you press enter?

Otherwise the current behavior seems to be that if you type a prefix, it'll show it and highlight it as the first suggestion, but pressing enter doesn't go to it, so you still end up having to type the entire name, defeating the purpose of the suggestion no? And pressing tab actually just makes the next selection be highlighted.

**Comment by blaenk** [comment]
Changing the selection to any other than the first does complete the entire name, but the first option is the correct one.

**Comment by ProLoser** [comment]
@blaenk it's supposed to do what you wanted it to do re: `pref`, but can you open a new issue (this appears to be a regression)?

**Comment by ProLoser** [comment]
Fixed by 03033a0
